FROM rykerrumsey/vim-base:v1.0

# NodeJS Packages
RUN npm i -g eslint \
  babel-eslint \
  eslint-plugin-react \
  prettier \
  eslint-config-prettier \
  eslint-plugin-prettier


# User config
ENV UID="1000" \
    UNAME="anonymous" \
    GID="1000" \
    GNAME="anonymous" \
    SHELL="/bin/bash" \
    UHOME=/home/anonymous


# User
RUN apk --no-cache add sudo \
# Create HOME dir
    && mkdir -p "${UHOME}" \
    && chown "${UID}":"${GID}" "${UHOME}" \
# Create user
    && echo "${UNAME}:x:${UID}:${GID}:${UNAME},,,:${UHOME}:${SHELL}" \
    >> /etc/passwd \
    && echo "${UNAME}::17032:0:99999:7:::" \
    >> /etc/shadow \
# No password sudo
    && echo "${UNAME} ALL=(ALL) NOPASSWD: ALL" \
    > "/etc/sudoers.d/${UNAME}" \
    && chmod 0440 "/etc/sudoers.d/${UNAME}" \
# Create group
    && echo "${GNAME}:x:${GID}:${UNAME}" \
    >> /etc/group

# Vim wrapper
COPY run /usr/local/bin/

COPY .vimrc $UHOME/.vimrc

# Vim plugins deps
RUN apk --no-cache add curl \
    && apk --update add \
    bash \
    ctags \
    curl \
    git \
    ncurses-terminfo \
    python \
    && apk add --virtual build-deps \
    build-base \
    cmake \
    llvm \
    perl \
    python-dev

RUN curl -fLo /home/anonymous/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

RUN ["vim", "-u", "$UHOME/.vimrc", "+PlugInstall", "+qall"]

# Cleanup
RUN apk del build-deps \
    curl \
    && apk add \
    libxt \
    libx11 \
    libstdc++ \
    && rm -rf \
    /var/cache/* \
    /var/log/* \
    /var/tmp/* \
    && mkdir /var/cache/apk

USER $UNAME

ENV TERM=xterm-256color

ENTRYPOINT ["sh", "/usr/local/bin/run"]
